
import Styles from "../styles/Tariff.module.css";
import {useEffect,useState} from "react"
import DotLoader from "react-spinners/DotLoader"
import PriceContainer from "../components/PriceContainer"

const tariff = () => {

    const loading = true;

    const data = [
        {
            "bikeNo": 1,
            "bikeName": "Honda Dio",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 2,
            "bikeName": "Activa 3G",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 3,
            "bikeName": "Activa 6G",
            "bikePriceWeekDay": 25,
            "bikePriceWeekEnd": 28,
            "bikePrice1WeekDay": 600,
            "bikePrice1WeekEnd": 672,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 5,
            "bikeName": "Aprilia 125",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 6,
            "bikeName": "Activa 150",
            "bikePriceWeekDay": 25,
            "bikePriceWeekEnd": 28,
            "bikePrice1WeekDay": 600,
            "bikePrice1WeekEnd": 672,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 7,
            "bikeName": "Ather",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 8,
            "bikeName": "Aviator",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 9,
            "bikeName": "Bajaj Pulsar",
            "bikePriceWeekDay": 30,
            "bikePriceWeekEnd": 35,
            "bikePrice1WeekDay": 720,
            "bikePrice1WeekEnd": 840,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 10,
            "bikeName": "Classic 350",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 11,
            "bikeName": "Continental GT 650",
            "bikePriceWeekDay": 95,
            "bikePriceWeekEnd": 110,
            "bikePrice1WeekDay": 2280,
            "bikePrice1WeekEnd": 2640,
            "bikePrice7": 5760,
            "bikePrice15": 9600,
            "bikePrice30": 20000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 8
        },
        {
            "bikeNo": 12,
            "bikeName": "Duke 200",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 13,
            "bikeName": "Epluto",
            "bikePriceWeekDay": 10,
            "bikePriceWeekEnd": 12,
            "bikePrice1WeekDay": 240,
            "bikePrice1WeekEnd": 288,
            "bikePrice7": 1600,
            "bikePrice15": 2800,
            "bikePrice30": 4000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "400",
            "kms15day": "700",
            "kms30day": "1000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 14,
            "bikeName": "Fascino",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 15,
            "bikeName": "FZ V1",
            "bikePriceWeekDay": 40,
            "bikePriceWeekEnd": 45,
            "bikePrice1WeekDay": 960,
            "bikePrice1WeekEnd": 1080,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 16,
            "bikeName": "Himalayan",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 17,
            "bikeName": "Activa 5G",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 18,
            "bikeName": "Honda CBR",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 19,
            "bikeName": "Honda Hornet",
            "bikePriceWeekDay": 30,
            "bikePriceWeekEnd": 35,
            "bikePrice1WeekDay": 720,
            "bikePrice1WeekEnd": 840,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 20,
            "bikeName": "Interceptor 650",
            "bikePriceWeekDay": 95,
            "bikePriceWeekEnd": 110,
            "bikePrice1WeekDay": 2280,
            "bikePrice1WeekEnd": 2640,
            "bikePrice7": 5760,
            "bikePrice15": 9600,
            "bikePrice30": 20000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 8
        },
        {
            "bikeNo": 21,
            "bikeName": "Jawa",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 22,
            "bikeName": "Mastreo",
            "bikePriceWeekDay": 20,
            "bikePriceWeekEnd": 22,
            "bikePrice1WeekDay": 480,
            "bikePrice1WeekEnd": 520,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 23,
            "bikeName": "Yamaha MT",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 24,
            "bikeName": "Ntorq",
            "bikePriceWeekDay": 25,
            "bikePriceWeekEnd": 28,
            "bikePrice1WeekDay": 600,
            "bikePrice1WeekEnd": 672,
            "bikePrice7": 2880,
            "bikePrice15": 6240,
            "bikePrice30": 8000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 25,
            "bikeName": "RE Desert Storm",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 26,
            "bikeName": "RE Stealth Black",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 27,
            "bikeName": "Thunderbird",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 28,
            "bikeName": "TVS XL",
            "bikePriceWeekDay": 10,
            "bikePriceWeekEnd": 12,
            "bikePrice1WeekDay": 240,
            "bikePrice1WeekEnd": 288,
            "bikePrice7": 1600,
            "bikePrice15": 2800,
            "bikePrice30": 4000,
            "city": "Bangalore",
            "kms1hour": "5",
            "kms1day": "120",
            "kms7day": "400",
            "kms15day": "700",
            "kms30day": "1000",
            "speedLimit": 80,
            "extraKmsCharge": 4
        },
        {
            "bikeNo": 29,
            "bikeName": "Xblade",
            "bikePriceWeekDay": 40,
            "bikePriceWeekEnd": 45,
            "bikePrice1WeekDay": 960,
            "bikePrice1WeekEnd": 1080,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 30,
            "bikeName": "Suzuki Gixer",
            "bikePriceWeekDay": 40,
            "bikePriceWeekEnd": 45,
            "bikePrice1WeekDay": 960,
            "bikePrice1WeekEnd": 1080,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 31,
            "bikeName": "Suzuki Gixer SF",
            "bikePriceWeekDay": 55,
            "bikePriceWeekEnd": 70,
            "bikePrice1WeekDay": 1320,
            "bikePrice1WeekEnd": 1680,
            "bikePrice7": 4320,
            "bikePrice15": 7200,
            "bikePrice30": 15000,
            "city": "Bangalore",
            "kms1hour": "12",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 6
        },
        {
            "bikeNo": 32,
            "bikeName": "Bajaj Avenger 220",
            "bikePriceWeekDay": 40,
            "bikePriceWeekEnd": 45,
            "bikePrice1WeekDay": 960,
            "bikePrice1WeekEnd": 1080,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2000",
            "speedLimit": 80,
            "extraKmsCharge": 5
        },
        {
            "bikeNo": 4,
            "bikeName": "Apache RTR 180",
            "bikePriceWeekDay": 40,
            "bikePriceWeekEnd": 45,
            "bikePrice1WeekDay": 960,
            "bikePrice1WeekEnd": 1080,
            "bikePrice7": 3600,
            "bikePrice15": 6000,
            "bikePrice30": 12500,
            "city": "Bangalore",
            "kms1hour": "10",
            "kms1day": "240",
            "kms7day": "720",
            "kms15day": "1200",
            "kms30day": "2500",
            "speedLimit": 80,
            "extraKmsCharge": 5
        }
    ]
    return (
        <div>
            <section >
                {data.length == 0? 
                <DotLoader color="#009387" loading={loading} css="display:block;margin:150px auto;" size={150} />:
                <div className="row" style={{margin:50}}>
                    {data.length !== 0?data.map((item,index)=>{
                            return <div className="col s12 m6 l4">
                                <PriceContainer key={index} data={item}/>
                                </div>
                        }):null}
                </div>}
            </section>
        </div>
    )
}

export default tariff
